### PR TITLE
Adding The Atkinson Hyperlegible and OpenDyslexic Fonts

### PR DESCRIPTION
**Pull request by KaiserCalm**
I have this font set up on my Steam Deck and since updates do seem to brake it a bit I thought I'd make a pull request to see if the font can be added to the list of fonts this extension uses.

### CODE REVIEW

**Comment by KaiserCalm** [comment]
The font can be downloaded from the Braille Institute and is meant to increase readability.

**Comment by EMERALD0874** [comment]
Fonts is not accepting new fonts at this time. I'll update the theme image at some point to indicate this.

**Comment by KaiserCalm** [comment]
@EMERALD0874 That's understandable, however I still think including this font or Open Dyslexic should be done, as not everyone is able to modify the plugin, especially when an update happens. These fonts serve to improve accessibility and in my opinion that's quite important, especially since there is no official way of changing the font at this time.

**Comment by EMERALD0874** [comment]
Actually, I see the accessibility benefits and will reconsider. I'll look at this soon.

**Comment by KaiserCalm** [comment]
Thank you! Would you like me to make a pull request for Open Dyslexic? I can try making a custom font too if necessary, I'd just need a link to the template.

**Comment by EMERALD0874** [comment]
Go for it if you want to. Don't worry about the custom font template, I was just saying to use that if you want to make a custom font that you won't upload here. Explains the steps and whatnot.

Please bundle the Open Dyslexic font with this PR.

**Comment by KaiserCalm** [comment]
Oooh, riiiight, now I remember the template, the thing I used to make this in the first place 🤦. Thank you, I'll go add the Open Dyslexic Font. 😀

**Comment by KaiserCalm** [comment]
I think I should be done. If anything needs fixing, please let me know.

**Review by EMERALD0874 — APPROVED** [review]
LGTM

**Pull request merged**
